id: A78638268
title: Prayer for the Long Life of Shechen Rabjam Rinpoche
type: translation
pechas:
- IA58AE4A7
- IDAFA8737
- IAB187A14
- I0330084A
- I661E00E6
- I1D4B5853
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:31.577292
  last_modified_at: 2023-01-04 11:37:31.577300
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IA58AE4A7/89E8: D2FC
  IDAFA8737/B429: D2FC
  IAB187A14/52AF: D2FC
  I0330084A/E2A3: D2FC
  I661E00E6/BB9F: D2FC
  I1D4B5853/CFA4: D2FC
